name: Fix Keystore
on:
  workflow_dispatch:
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print keystore as base64
        run: |
          base64 -w 0 my-upload-key.jks
